// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20240718041755_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7784749-1d36-41b4-9c5c-c7547835af90"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("da435085-fa7b-478e-a975-eea82c2cbde6"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("68cedbfc-f43f-4f96-870e-41f1296ffd4f"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0922d3ca-37df-44e0-8874-297ffdde3399"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://www.distantjourneys.co.uk/wp-content/uploads/2018/03/auckland-sky-tower-at-night-new-zealand.jpg"
                        },
                        new
                        {
                            Id = new Guid("56ecd709-dc48-4ad0-ae72-db687141244d"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "https://www.civitatis.com/f/australia/byron-bay/byron-bay-m.jpg"
                        },
                        new
                        {
                            Id = new Guid("7b8308d4-2cae-4658-873f-b43435504e7b"),
                            Code = "BOP",
                            Name = "Bey of Plenty",
                            RegionImageUrl = "https://lp-cms-production.imgix.net/image_browser/GettyImages-103581610.jpg?auto=format&fit=crop&sharp=10&vib=20&ixlib=react-8.6.4&w=850&q=20&dpr=5"
                        },
                        new
                        {
                            Id = new Guid("0541fd0d-403e-4783-95d2-877848f49773"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://th.bing.com/th/id/OIP.58LIsvmhTiieG_6pTm7FIAHaE8?rs=1&pid=ImgDetMain"
                        },
                        new
                        {
                            Id = new Guid("f6605d3f-0269-46d8-a023-a12a20810b6d"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://th.bing.com/th/id/OIP.FRYxO84ju7dLdC8ymUSCpwHaEK?rs=1&pid=ImgDetMain"
                        },
                        new
                        {
                            Id = new Guid("80853b49-c740-4a7a-9a0b-bbf8d07be58e"),
                            Code = "STL",
                            Name = "Southland",
                            RegionImageUrl = "https://th.bing.com/th/id/OIP.9O3-I4uO5XgoQ9QmGIKi6QHaEK?rs=1&pid=ImgDetMain"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
